/** biome-ignore-all lint/complexity/useSimpleNumberKeys: Firmware addr in hex */
import type { MachineConfig } from "@/types/machine.interface";

export const debugConfig: MachineConfig["debugOptions"] = [
	{
		id: "lcView",
		label: "LC ROM",
		type: "select",
		category: "memory",
		options: [
			{ label: "Auto", value: "AUTO" },
			{ label: "ROM", value: "ROM" },
			{ label: "LC Bank 1", value: "BANK1" },
			{ label: "LC Bank 2", value: "BANK2" },
		],
	},
	{
		id: "cxView",
		label: "Cx ROM",
		type: "select",
		category: "memory",
		options: [
			{ label: "Auto", value: "AUTO" },
			{ label: "Internal", value: "INT" },
			{ label: "Slots", value: "SLOT" },
		],
	},
	{
		id: "videoMode",
		label: "Video Mode",
		type: "select",
		category: "video",
		group: "Mode",
		options: [
			{ label: "Auto", value: "AUTO" },
			{ label: "Text", value: "TEXT" },
			{ label: "HGR", value: "HGR" },
		],
	},
	{
		id: "videoPage",
		label: "Video Page",
		type: "select",
		category: "video",
		group: "Mode",
		options: [
			{ label: "Auto", value: "AUTO" },
			{ label: "Page 1", value: "PAGE1" },
			{ label: "Page 2", value: "PAGE2" },
		],
	},
	{
		id: "textRenderer",
		label: "Text Renderer",
		type: "select",
		category: "video",
		group: "Text",
		savable: true,
		options: [
			{ label: "Font", value: "FONT" },
			{ label: "Bitmap", value: "BITMAP" },
		],
	},
	{
		id: "mouseChars",
		label: "Mouse Chars",
		type: "select",
		category: "video",
		group: "Text",
		options: [
			{ label: "Auto", value: "AUTO" },
			{ label: "Mouse Chars", value: "ON" },
			{ label: "Normal Chars", value: "OFF" },
		],
	},
	{
		id: "textFgColor",
		label: "FG",
		type: "select",
		category: "video",
		group: "Text",
		row: "textColor",
		defaultValue: -1,
		savable: true,
		options: [
			{ label: "Auto", value: -1 },
			{ label: "Black", value: 0 },
			{ label: "D. Red", value: 1 },
			{ label: "D. Blue", value: 2 },
			{ label: "Purple", value: 3 },
			{ label: "D. Green", value: 4 },
			{ label: "D. Gray", value: 5 },
			{ label: "M. Blue", value: 6 },
			{ label: "Brown", value: 8 }, // Note: 8 is Brown in IIgs palette
			{ label: "Orange", value: 9 },
			{ label: "L. Gray", value: 10 },
			{ label: "Pink", value: 11 },
			{ label: "L. Green", value: 12 },
			{ label: "Yellow", value: 13 },
			{ label: "Aquamarine", value: 14 },
			{ label: "White", value: 15 },
		],
	},
	{
		id: "textBgColor",
		label: "BG",
		type: "select",
		category: "video",
		group: "Text",
		row: "textColor",
		defaultValue: -1,
		savable: true,
		options: [
			{ label: "Auto", value: -1 },
			{ label: "Black", value: 0 },
			{ label: "D. Red", value: 1 },
			{ label: "D. Blue", value: 2 },
			{ label: "Purple", value: 3 },
			{ label: "D. Green", value: 4 },
			{ label: "D. Gray", value: 5 },
			{ label: "M. Blue", value: 6 },
			{ label: "Brown", value: 8 },
			{ label: "Orange", value: 9 },
			{ label: "L. Gray", value: 10 },
			{ label: "Pink", value: 11 },
			{ label: "L. Green", value: 12 },
			{ label: "Yellow", value: 13 },
			{ label: "Aquamarine", value: 14 },
			{ label: "White", value: 15 },
		],
	},
	{
		id: "borderColor",
		label: "Border Color",
		type: "select",
		category: "video",
		group: "Display",
		defaultValue: -1,
		savable: true,
		options: [
			{ label: "Auto", value: -1 },
			{ label: "Black", value: 0 },
			{ label: "D. Red", value: 1 },
			{ label: "D. Blue", value: 2 },
			{ label: "Purple", value: 3 },
			{ label: "D. Green", value: 4 },
			{ label: "D. Gray", value: 5 },
			{ label: "M. Blue", value: 6 },
			{ label: "Brown", value: 8 },
			{ label: "Orange", value: 9 },
			{ label: "L. Gray", value: 10 },
			{ label: "Pink", value: 11 },
			{ label: "L. Green", value: 12 },
			{ label: "Yellow", value: 13 },
			{ label: "Aquamarine", value: 14 },
			{ label: "White", value: 15 },
		],
	},
	{
		id: "wannaScale",
		label: "Scale",
		type: "boolean",
		category: "video",
		group: "Dimensions",
	},
	{
		id: "canvasSize",
		label: "Canvas Size",
		type: "select",
		category: "video",
		group: "Dimensions",
		savable: true,
		options: [
			{ label: "Auto", value: "AUTO" },
			{ label: "Custom", value: "CUSTOM" },
		],
	},
	{
		id: "customWidth",
		label: "Width",
		type: "number",
		category: "video",
		group: "Dimensions",
		row: "size",
		savable: true,
		defaultValue: 640,
		disableIf: { optionId: "canvasSize", value: "AUTO" },
	},
	{
		id: "customHeight",
		label: "Height",
		type: "number",
		category: "video",
		group: "Dimensions",
		row: "size",
		savable: true,
		defaultValue: 480,
		disableIf: { optionId: "canvasSize", value: "AUTO" },
	},
];
